# 向量, 矩阵基本操作

In [1]:
import numpy as np

生成一个array, 可以通过一个list生成一个array, 也可以通过内置的一些特殊的函数生成一个array

In [2]:
a1 = np.array([1,2,3,4,5,6])
a2 = np.arange(1,7)
a3 = np.linspace(1,6,6,dtype='int')
print('a1:', a1)
print('a2:', a2)
print('a3:', a3)

a1: [1 2 3 4 5 6]
a2: [1 2 3 4 5 6]
a3: [1 2 3 4 5 6]


# 一维array的基本属性

In [3]:
print('shape:',np.shape(a1)) # 返回数组的维度, 一个元组
print('size:', np.size(a1)) # 返回数组的元素的个数

shape: (6,)
size: 6


In [4]:
print(type(a1))#查看类型
print(a1.dtype) #查看数组中的数据类型
print(a1.itemsize)#查看每个元素占据的字节
print(a1.nbytes) # 查看所有元素占据的字节
print(a1.ndim) # 查看数组的维数

<class 'numpy.ndarray'>
int64
8
48
1


使用fill函数可以设定初始值

In [5]:
a1.fill(4.3)
print(a1) # fill函数会保持原有数组的数据类型不变int 仍然为int, 如果不是则将其转化为相应的类型

[4 4 4 4 4 4]


# 索引和切片

array的数组的索引与list一样, 都是从0开始.

In [6]:
for i in range(6):
    print(a2[i])

1
2
3
4
5
6


当然也支持负索引

In [7]:
for i in range(-1,-7,-1):
    print(a2[i])

6
5
4
3
2
1


切片

In [8]:
a2 = np.array([1,2,3,4,5,6])

In [9]:
a2[1:3]

array([2, 3])

In [10]:
a2[:3]

array([1, 2, 3])

In [11]:
a2[-3:]

array([4, 5, 6])

In [12]:
a2[::2]

array([1, 3, 5])

In [13]:
a2[1::2]

array([2, 4, 6])

# 多维数组的基本属性

In [14]:
b1 = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
print(type(b1))
print(b1.dtype)
print(np.shape(b1))
print(np.size(b1))
print(b1.itemsize)
print(b1.nbytes)#
print(b1.ndim)

<class 'numpy.ndarray'>
int64
(2, 4)
8
8
64
2


In [16]:
b1[1,2]

7

In [17]:
b1[1]

array([5, 6, 7, 8])

In [18]:
b1[1][2]

7

# 多维数组的切片

In [19]:
b2 = np.arange(24).reshape((4,6))
b2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
b2[1:2,::2] #生成的还是二维数组

array([[ 6,  8, 10]])

In [21]:
b2[-2:,-2:]

array([[16, 17],
       [22, 23]])

注意切片是引用, 也即为浅拷贝, 而不是深拷贝

In [22]:
b3 = b2[1]
b3[1] = 100
b3

array([  6, 100,   8,   9,  10,  11])

In [23]:
b2

array([[  0,   1,   2,   3,   4,   5],
       [  6, 100,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

对于一个列表(list)来说, 切片都是深拷贝, 而array不是, 所以如果希望使用深拷贝, 就需要使用copy方法

In [24]:
b3 = b2[0].copy()
b3[1] = 100
b3

array([  0, 100,   2,   3,   4,   5])

In [25]:
b2

array([[  0,   1,   2,   3,   4,   5],
       [  6, 100,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23]])

# 花式索引 fancy slicing

切片只可以产生等间隔的切片操作, 花式索引可以实现任意位置的索引

In [26]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
slc = [1,8,5,9]
a[slc]

array([ 2,  9,  6, 10])

也可以使用bool数组实现花式索引

In [27]:
slc = np.array([0,0,1,1,0,0,0,1,1,0],dtype=bool)
a[slc]

array([3, 4, 8, 9])

In [28]:
slc = a > 4
a[slc]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10])

二维数组的花式索引

In [30]:
b = np.arange(24).reshape((4,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
b[(0,1,2,3),(1,2,3,4)]

array([ 1,  8, 15, 22])

In [32]:
b[1:, [0,2,5]]

array([[ 6,  8, 11],
       [12, 14, 17],
       [18, 20, 23]])

可以看到花式索引是对原数组的复制(深拷贝)而不是引用(浅拷贝)

In [33]:
b1 = b[1:, [0,2,5]]
b1[1,2] = 100
b1

array([[  6,   8,  11],
       [ 12,  14, 100],
       [ 18,  20,  23]])

In [34]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# where语句

In [35]:
a = np.array([1,2,3,10,20,30])

In [36]:
np.where(a>10)

(array([4, 5]),)

In [37]:
a = np.arange(24).reshape((4,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
np.where(a>20)

(array([3, 3, 3]), array([3, 4, 5]))

In [39]:
row, col = np.where(a>20)
print('row:', row)
print('col:', col)

row: [3 3 3]
col: [3 4 5]


In [40]:
a>20

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True,  True]], dtype=bool)

In [41]:
a[a>20] #生成一个一维的array

array([21, 22, 23])

# 数组类型

数组在产生的时候, 如果不指定数据类型, 系统会自动识别类型

In [42]:
a = np.array([1,2,3.45,5,6,7])

In [43]:
a.dtype

dtype('float64')

In [44]:
a.nbytes

48

In [45]:
a.itemsize

8

当然我们也可以指定数据类型

In [46]:
a = np.array([1,2,3.45,5,6,7],dtype=int)

In [47]:
a

array([1, 2, 3, 5, 6, 7])

In [48]:
a.dtype

dtype('int64')

In [49]:
a.itemsize

8

# Numpy的数据类型

具体如下：

|基本类型|可用的**Numpy**类型|备注
|--|--|--
|布尔型|`bool`|占1个字节
|整型|`int8, int16, int32, int64, int128, int`| `int` 跟**C**语言中的 `long` 一样大
|无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`| `uint` 跟**C**语言中的 `unsigned long` 一样大
|浮点数| `float16, float32, float64, float, longfloat`|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
|复数| `complex64, complex128, complex, longcomplex`| 默认为 `complex128` ，即实部虚部都为双精度
|字符串| `string, unicode` | 可以使用 `dtype=S4` 表示一个4字节字符串的数组
|对象| `object` |数组中可以使用任意值|
|Records| `void` ||
|时间| `datetime64, timedelta64` ||

任意类型的数组：

In [50]:
a = np.array([1,2.34,'afsgda',[1,2,3,4],(1,2,3)],dtype=object)

In [51]:
a*2

array([2, 4.68, 'afsgdaafsgda', list([1, 2, 3, 4, 1, 2, 3, 4]),
       (1, 2, 3, 1, 2, 3)], dtype=object)

# 类型转换

In [52]:
#astype
a = np.array([1,2,3.24,5,6,7])
a

array([ 1.  ,  2.  ,  3.24,  5.  ,  6.  ,  7.  ])

In [53]:
a.astype('int')# 但是实际上a并没有改变

array([1, 2, 3, 5, 6, 7])

In [54]:
a

array([ 1.  ,  2.  ,  3.24,  5.  ,  6.  ,  7.  ])

In [55]:
a = a.astype('int')
a

array([1, 2, 3, 5, 6, 7])

In [56]:
# asarry
a = np.array([1,2,3.24,5,6,7])
a = np.asarray(a, dtype=int)
a

array([1, 2, 3, 5, 6, 7])

In [57]:
#view
a = np.array([1.12,2,3,4],dtype=np.int32)
b = a.view(np.int32)
b

array([1, 2, 3, 4], dtype=int32)

`view` 会将 `a` 在内存中的表示看成是 `uint8` 进行解析：

In [58]:
b = a.view(np.uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [59]:
a[0] = 5

In [60]:
print('a:', a)
print('b:',b)#这个是浅拷贝

a: [5 2 3 4]
b: [5 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0]


In [61]:
b.dtype

dtype('uint8')