# 数组的常见操作

In [1]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])

# 求和

In [2]:
print(np.sum(a)) #求和
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

36
[ 6  8 10 12]
[10 26]


# 求积

In [3]:
print(np.prod(a)) #求积
print(np.prod(a, axis=0))
print(np.prod(a, axis=1))

40320
[ 5 12 21 32]
[  24 1680]


# 求最大最小

In [4]:
print(np.min(a)) # 求最小
print(np.min(a, axis=0))
print(np.min(a, axis=1))

1
[1 2 3 4]
[1 5]


In [5]:
print(np.max(a)) # 求最大
print(np.max(a, axis=0))
print(np.max(a, axis=1))

8
[5 6 7 8]
[4 8]


# 求最大最小位置

In [6]:
print(np.argmin(a))
print(np.argmax(a))

0
7


我们使用一些运算将其变成索引

In [7]:
pos = np.argmax(a)
_,col = np.shape(a)
posx,posy = pos//col, pos%col
(posx, posy)#最大值的位置

(1, 3)

# 求平均值

In [8]:
np.mean(a)

4.5

average函数, 还支持加权平均数

In [9]:
np.average(a, axis=0, weights=[1,2])

array([ 3.66666667,  4.66666667,  5.66666667,  6.66666667])

# 求方差, 标准差

In [10]:
print('var', np.var(a))
print('std', np.std(a))

var 5.25
std 2.29128784748


In [11]:
print('var', np.var(a, axis=0))
print('std', np.std(a, axis=1))

var [ 4.  4.  4.  4.]
std [ 1.11803399  1.11803399]


clip方法, 将数据限制在某个范围内

In [12]:
a = np.arange(10).reshape((5,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [13]:
a.clip(3,5)

array([[3, 3],
       [3, 3],
       [4, 5],
       [5, 5],
       [5, 5]])

# ptp方法, 计算最大最小值的差值

In [14]:
print(a.ptp())
print(a.ptp(axis=0))

9
[8 8]


# round 方法

In [15]:
a = np.array([1,2.4,3.43536465,2.235,1.3467])
b = np.round(a)
print(b)#默认到整数, 实际上的浮点数
print(b.dtype)

[ 1.  2.  3.  2.  1.]
float64


In [16]:
b = np.round(a,decimals=2)
print(b)#默认到整数, 实际上的浮点数
print(b.dtype)

[ 1.    2.4   3.44  2.24  1.35]
float64


# 排序

In [17]:
a = np.array([1,4,2,5,6,3,9,10,13,12,11])
print(np.sort(a))#输出排序后的结果
print(a)

[ 1  2  3  4  5  6  9 10 11 12 13]
[ 1  4  2  5  6  3  9 10 13 12 11]


In [18]:
index = np.argsort(a)
a[index]
#np.sort(a) == a[np.argsort(a)]

array([ 1,  2,  3,  4,  5,  6,  9, 10, 11, 12, 13])

In [19]:
a = np.array([[3,1],[2,8]])

In [20]:
np.sort(a, axis=None)

array([1, 2, 3, 8])

In [21]:
np.sort(a, axis=0)

array([[2, 1],
       [3, 8]])

In [22]:
np.sort(a, axis=1)

array([[1, 3],
       [2, 8]])

sort函数还可以实现关键字排序

In [23]:
key=[('name', 'S10'),('height','float'),('age', 'int')]
person = np.array([('A',175.2, 20), ('B', 165.2, 25), ('C', 183, 26)],dtype=key)

In [24]:
np.sort(person, order='height')

array([(b'B',  165.2, 25), (b'A',  175.2, 20), (b'C',  183. , 26)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

实现类似matlab中sortrows的功能

sortrows的功能在于可以实现有限排序, 例如对于一个二维数组, 我们可以优先第一列排序, 其次是第二列, 第三列, 知道最后一列

In [25]:
a = [(1,2,4,5,7),(1,3,4,6,9),(1,2,3,4,5),(1,3,5,6,8)]

In [26]:
key = [(str(i), int) for i in range(5)]
a = np.array(a, dtype=key)
b = np.sort(a, order=[str(i) for i in range(5)])# 这个是实现从一列最高优先, 其次是第二列， 第三列，直到最后一列
print(b)

[(1, 2, 3, 4, 5) (1, 2, 4, 5, 7) (1, 3, 4, 6, 9) (1, 3, 5, 6, 8)]


In [27]:
key = [(str(i), int) for i in range(5)]
a = np.array(a, dtype=key)
b = np.sort(a, order=[str(i) for i in [3, 4]])# 这个是实现优先第四列, 其次是第五列
print(b)

[(1, 2, 3, 4, 5) (1, 2, 4, 5, 7) (1, 3, 5, 6, 8) (1, 3, 4, 6, 9)]


# searchsorted 函数

    searchsorted(sorted_array, values)

`searchsorted` 接受两个参数，其中，第一个必需是已排序的数组。

In [28]:
sorted_array = np.linspace(0,1,5)
values = np.array([.1,.8,.3,.12,.5,.25])
np.searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1])

排序数组：

|0|1|2|3|4|
|-|-|-|-|-|
|0.0|0.25|0.5|0.75|1.0

数值：

|值|0.1|0.8|0.3|0.12|0.5|0.25|
|-|-|-|-|-|-|-|
|插入位置|1|4|2|1|2|1|

`searchsorted` 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 `0.1` 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 `1` 处，故第一个返回值为 `1`。

In [29]:
data = np.array([0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0])
data.sort()
bounds = .4, .6
low_idx, high_idx = np.searchsorted(data, bounds)
data[low_idx:high_idx]#输出在0.4到0.6之间的数据，左开右闭

array([ 0.4,  0.5])