In [1]:
import numpy as np
a = np.arange(16)

# 使用reshape可以将其变成不同维度的矩阵

In [2]:
a.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
a.reshape((8,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

# 使用 newaxis 增加数组维数

In [4]:
a = a.reshape((4,4))
a = a[np.newaxis, :]
a.shape

(1, 4, 4)

# squeezeh方法
事实上, 多于的维数很多时候会带来麻烦, 使用squeezeh方法可以删除多于的维度

In [5]:
a = np.squeeze(a)
a.shape

(4, 4)

# 转置
使用 transpose 返回数组的转置，本质上是将所有维度反过来：

In [6]:
a = np.arange(8)
a = a.reshape((4,2,1))
a

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]],

       [[6],
        [7]]])

In [7]:
b = np.transpose(a)
b.shape#将所有的维度全部反过来

(1, 2, 4)

转置返回的是对原数组的另一种view，所以改变转置会改变原来数组的值。

In [8]:
b[0,1,1] = 100
print('a:', a)
print('b:', b)

a: [[[  0]
  [  1]]

 [[  2]
  [100]]

 [[  4]
  [  5]]

 [[  6]
  [  7]]]
b: [[[  0   2   4   6]
  [  1 100   5   7]]]


高维数组的转置

In [9]:
a = np.arange(16).reshape((2,2,4))
print('a:\n', a)
print('a.shape:,', a.shape)
b = a.transpose((2,0,1))#实际上就是吧原来的0,1,2轴变成2,0,1轴
print('b:\n',b)
print('b.shape:', b.shape)

a:
 [[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
a.shape:, (2, 2, 4)
b:
 [[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]
b.shape: (4, 2, 2)


# 数组对接

In [10]:
x = np.array([
        [0,1,2],
        [10,11,12]
    ])
y = np.array([
        [50,51,52],
        [60,61,62]
    ])
z = np.concatenate((x, y))#默认为axis=0
print(z)

[[ 0  1  2]
 [10 11 12]
 [50 51 52]
 [60 61 62]]


In [11]:
z = np.concatenate((x, y), axis=1)
print(z)

[[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]


还有 vstack, hstack两种用来竖直方向对接和水平方向对接的函数

In [12]:
z1 = np.vstack((x, y))
z2 = np.hstack((x, y))
print('z1:\n', z1)
print('z2:\n', z2)

z1:
 [[ 0  1  2]
 [10 11 12]
 [50 51 52]
 [60 61 62]]
z2:
 [[ 0  1  2 50 51 52]
 [10 11 12 60 61 62]]


实际上这里x, y很特别, 它们的维度完全一致, 所以可以在一个新的方向上对接

In [13]:
z1 = np.array((x, y))
z2 = np.dstack((x, y))
print('z1:', z1)
print('z2:', z2)

z1: [[[ 0  1  2]
  [10 11 12]]

 [[50 51 52]
  [60 61 62]]]
z2: [[[ 0 50]
  [ 1 51]
  [ 2 52]]

 [[10 60]
  [11 61]
  [12 62]]]


# flatten 数组

`flatten` 方法的作用是将多维数组转化为1维数组：

In [14]:
a = np.array([[1,2,3,4],[2,3,4,5]])
b = a.flatten()
b[1] = 100
print('a:\n', a)
print('b:\n', b)#flatten是对数组的复制,深拷贝

a:
 [[1 2 3 4]
 [2 3 4 5]]
b:
 [  1 100   3   4   2   3   4   5]


数组本身有一个flat属性, 可以返回一个迭代器

In [15]:
b = a.flat
b[1] = 100
print('b:\n', np.array(b))
print('a:\n', a)#此时修改就会改变原有数组的值了

b:
 [  1 100   3   4   2   3   4   5]
a:
 [[  1 100   3   4]
 [  2   3   4   5]]


此外还可以使用ravel函数

In [16]:
a = np.array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

修改b会改变a的数值

In [17]:
b[1] = 100
print('a:\n', a)
print('b:\n', b)

a:
 [[  0 100]
 [  2   3]]
b:
 [  0 100   2   3]


但是这种情况下不会修改原有数组的值

In [18]:
a = np.array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [19]:
b[0] = 100
print(aa)
print(a)

[[0 2]
 [1 3]]
[[0 1]
 [2 3]]


# atleast_xd 函数, x=1,2,3

用于预处理, 保证数组有x dimensions

In [20]:
a = np.array([1,2,3])
b = np.atleast_2d(a)
b.shape

(1, 3)

In [21]:
a = np.array([1,2,3])
b = np.atleast_3d(a)
b.shape

(1, 3, 1)

# diagonal 函数

In [22]:
a = np.arange(16).reshape((4,4))
np.diagonal(a)

array([ 0,  5, 10, 15])

In [23]:
a.diagonal()

array([ 0,  5, 10, 15])

使用偏移offset用来查看↗和↙对角线,offset正数表示向右上偏移, 负值表示向左下偏移

In [24]:
a.diagonal(offset=1)

array([ 1,  6, 11])

In [25]:
a.diagonal(offset=-1)

array([ 4,  9, 14])

也可以使用花式索引来获取对角线元素

In [26]:
row,col = np.shape(a)
i = range(row)
a[i,i]

array([ 0,  5, 10, 15])

In [27]:
a[i, i] = 100#修改对角线的数值
a

array([[100,   1,   2,   3],
       [  4, 100,   6,   7],
       [  8,   9, 100,  11],
       [ 12,  13,  14, 100]])

# 数组与字符串的转换

In [28]:
a = np.array([[1,2,3,4],[2,3,4,5]],dtype=np.uint8)
s = a.tostring()
print(s)

b'\x01\x02\x03\x04\x02\x03\x04\x05'


# fromstring 函数
使用fromstring函数进行吧字符串解码成原数组

In [29]:
aa = np.fromstring(s, dtype=np.uint8)
aa

array([1, 2, 3, 4, 2, 3, 4, 5], dtype=uint8)

可以看到此时数组变成了一维数组, reshape一下就可以了

In [30]:
aa.reshape((2,4))

array([[1, 2, 3, 4],
       [2, 3, 4, 5]], dtype=uint8)

# summary
数组属性的方法总结

||作用|
|-|-|
|1|**基本属性**
|`a.dtype`|数组元素类型 `float32,uint8,...`
|`a.shape`|数组形状 `(m,n,o,...)`
|`a.size`|数组元素数
|`a.itemsize`|每个元素占字节数
|`a.nbytes`|所有元素占的字节
|`a.ndim`|数组维度
|2|**形状相关**
|`a.flat`|所有元素的迭代器 (浅拷贝)
|`a.flatten()`|返回一个1维数组的复制 (深拷贝)
|`a.ravel()`|返回一个1维数组，高效 (浅拷贝)
|`a.resize(new_size)`|改变形状
|`a.swapaxes(axis1, axis2)`|交换两个维度的位置
|`a.transpose(*axex)`|交换所有维度的位置
|`a.T`|转置，`a.transpose()`
|`a.squeeze()`| 去除所有长度为1的维度
|3|**填充复制**
|`a.copy()`| 返回数组的一个复制
|`a.fill(value)`| 将数组的元组设置为特定值
|4|**转化**
|`a.tolist()`|将数组转化为列表
|`a.tostring()`|转换为字符串
|`a.astype(dtype)`|转化为指定类型
|`a.byteswap(False)`|转换大小字节序
|`a.view(type_or_dtype)`|生成一个使用相同内存，但使用不同的表示方法的数组
|5|**复数**
|`a.imag`|虚部
|`a.real`|实部
|`a.conjugate()`|复共轭
|`a.conj()`|复共轭（缩写）
|6|**保存**
|`a.dump(file)`|将二进制数据存在file中, dump-load
|`a.dumps()`|将二进制数据表示成字符串, dumps-loads
|`a.tofile(fid, sep="",format="%s")`|格式化ASCⅡ码写入文件
|7|**查找排序**
|`a.nonzero()`|返回所有非零元素的索引
|`a.sort(axis=-1)`|沿某个轴排序
|`a.argsort(axis=-1)`|沿某个轴，返回按排序的索引
|`a.searchsorted(b)`|返回将b中元素插入a后能保持有序的索引值
|8|**元素数学操作**
|`a.clip(low, high)`|将数值限制在一定范围内
|`a.round(decimals=0)`|近似到指定精度
|`a.cumsum(axis=None)`|累加和
|`a.cumprod(axis=None)`|累乘积
|9|**约简操作**
|`a.sum(axis=None)`|求和
|`a.prod(axis=None)`|求积
|`a.min(axis=None)`|最小值
|`a.max(axis=None)`|最大值
|`a.argmin(axis=None)`|最小值索引
|`a.argmax(axis=None)`|最大值索引
|`a.ptp(axis=None)`|最大值减最小值
|`a.mean(axis=None)`|平均值
|`a.std(axis=None)`|标准差
|`a.var(axis=None)`|方差
|`a.any(axis=None)`|只要有一个不为0，返回真，逻辑或
|`a.all(axis=None)`|所有都不为0，返回真，逻辑与

# 基本属性

In [31]:
a = np.array([1,2,3,4,5,6])

In [32]:
a.dtype

dtype('int64')

In [33]:
a.shape

(6,)

In [34]:
a.size

6

In [35]:
a.itemsize

8

In [36]:
a.nbytes

48

In [37]:
a.ndim

1

# 形状相关

In [38]:
a = np.arange(12).reshape((4,3))
b = a.flat
b[0] = 100#浅拷贝
print(a)

[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [39]:
a = np.arange(12).reshape((4,3))
b = a.flatten()#深拷贝
b[0] = 100
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [40]:
a = np.arange(12).reshape((4,3))
b = a.ravel()#浅拷贝
b[0] = 100
print(a)

[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [41]:
a.resize((3,4))
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [42]:
a = np.arange(12).reshape((4,3))
a.swapaxes(0,1)# 交换axis=0和axis=1的位置，其实就是转置

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [43]:
a = np.arange(12).reshape((4,3))
a.swapaxes(1,0)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [44]:
a = np.arange(12).reshape((4,3,1))
a.transpose().shape

(1, 3, 4)

In [45]:
a = np.arange(12).reshape((4,3,1))
a.squeeze()#去除多余的维度

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# 填充复制

In [46]:
a = np.arange(12)
b = a.copy()
b[0] = 100
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [47]:
a.fill(100)
print(a)

[100 100 100 100 100 100 100 100 100 100 100 100]


# 转化

In [48]:
a = np.arange(12)
a.tolist()#变成一个列表

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [49]:
a.tostring()

b'\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00'

In [50]:
a = a.astype('float')
print(a)

[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]


In [51]:
a.view(dtype=int) #生成一个使用相同内存，但使用不同的表示方法的数组

array([                  0, 4607182418800017408, 4611686018427387904,
       4613937818241073152, 4616189618054758400, 4617315517961601024,
       4618441417868443648, 4619567317775286272, 4620693217682128896,
       4621256167635550208, 4621819117588971520, 4622382067542392832])

# 复数

In [52]:
a = np.complex(1,1)
print('real part:', a.real)
print('imagine part',a.imag)

real part: 1.0
imagine part 1.0


In [53]:
a.conjugate()

(1-1j)

# 保存

In [54]:
a = np.arange(12)
a.dump('a.csv')#保存

In [55]:
np.load('a.csv')#重载

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [56]:
s = a.dumps()#保存为字符串

In [57]:
np.loads(s)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a.tofile('a.csv', sep=',', format='%s')

# 查找排序

In [59]:
a = np.arange(12)
a.nonzero() #返回所有不为零的元素的索引

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),)

In [60]:
np.sort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [61]:
np.argsort(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
a.searchsorted(2.31) #将b插入a中正确排序的位置

3

# 元素的数学操作

In [63]:
a = np.arange(12)
a.clip(6,10)#超过范围的均按照边界取值

array([ 6,  6,  6,  6,  6,  6,  6,  7,  8,  9, 10, 10])

In [64]:
a = np.array([1,2,3.123123,5.235345,1.35,1.35654])
print(a.round())
print(a.round(decimals=1))#默认decimals=0, 也就是小数点后没有数

[ 1.  2.  3.  5.  1.  1.]
[ 1.   2.   3.1  5.2  1.4  1.4]


In [65]:
a.cumsum()#累积和

array([  1.      ,   3.      ,   6.123123,  11.358468,  12.708468,
        14.065008])

In [66]:
a.cumprod()#累积乘积

array([  1.        ,   2.        ,   6.246246  ,  32.70125276,
        44.14669123,  59.88675252])

# 约简操作

In [67]:
a = np.random.rand(10)

In [68]:
a.sum()#求和

4.8179415164543284

In [69]:
a.prod()#求积

9.8027817136320415e-05

In [70]:
a.min()

0.16185120100319217

In [71]:
a.max()

0.93072002510070628

In [72]:
t = (a.argmin(), a.argmax())
t

(5, 4)

In [73]:
a.ptp()#最大值减去最小值

0.76886882409751411

In [74]:
a.mean()#平均值

0.48179415164543282

In [75]:
a.std()#标准差

0.2873674487566068

In [76]:
a.var()#方差

0.082580050604881036

In [77]:
a.any()

True

In [78]:
a.all()

True