# 一般函数

In [1]:
import numpy as np

## 三角函数

    sin(x)
    cos(x)
    tan(x)
    sinh(x)
    conh(x)
    tanh(x)
    arccos(x)
    arctan(x)
    arcsin(x)
    arccosh(x)
    arctanh(x)
    arcsinh(x)
    arctan2(x,y)

`arctan2(x,y)` 返回 `arctan(x/y)` 。

In [2]:
x1 = np.arange(0,1,0.2)
print('sin(x1):', np.sin(x1))
print('cos(x1):', np.cos(x1))
print('tan(x1):', np.tan(x1))
print('sinh(x1):', np.sinh(x1))
print('cosh(x1):', np.cosh(x1))
print('tanh(x1):', np.tanh(x1))
print('arcsin(x1):', np.arcsin(x1))
print('arccos(x1):', np.arccos(x1))
print('arctan(x1):', np.arctan(x1))
print('arcsinh(x1):', np.arcsinh(x1))
print('arccosh(x1+1):', np.arccosh(x1+1))
print('arctanh(x1):', np.arctanh(x1))
x = np.arange(1,2,0.2)
y = np.arange(2,1,-0.2)
print('arctan2(x,y):', np.arctan2(x,y))

sin(x1): [0.         0.19866933 0.38941834 0.56464247 0.71735609]
cos(x1): [1.         0.98006658 0.92106099 0.82533561 0.69670671]
tan(x1): [0.         0.20271004 0.42279322 0.68413681 1.02963856]
sinh(x1): [0.         0.201336   0.41075233 0.63665358 0.88810598]
cosh(x1): [1.         1.02006676 1.08107237 1.18546522 1.33743495]
tanh(x1): [0.         0.19737532 0.37994896 0.53704957 0.66403677]
arcsin(x1): [0.         0.20135792 0.41151685 0.64350111 0.92729522]
arccos(x1): [1.57079633 1.36943841 1.15927948 0.92729522 0.64350111]
arctan(x1): [0.         0.19739556 0.38050638 0.5404195  0.67474094]
arcsinh(x1): [0.         0.19869011 0.39003532 0.5688249  0.73266826]
arccosh(x1+1): [0.         0.6223625  0.86701473 1.04696792 1.19291073]
arctanh(x1): [0.         0.20273255 0.42364893 0.69314718 1.09861229]
arctan2(x,y): [0.46364761 0.5880026  0.71883    0.85196633 0.98279372]


## 向量操作, 各种积的函数

    dot(x,y)
    inner(x,y)
    cross(x,y)
    vdot(x,y)
    outer(x,y)
    kron(x,y)
    tensordot(x,y[,axis])

## dot 

`numpy.dot(a, b, out=None)`
Dot product of two arrays. Specifically,

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

- If both a and b are 2-D arrays, it is matrix multiplication, but using `matmul` or `a @ b` is preferred.

- If either a or b is 0-D (scalar), it is equivalent to multiply and using `numpy.multiply(a, b)` or `a * b` is preferred.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

- If a is an N-D array and b is an M-D array (where `M>=2`), it is a sum product over the last axis of a and the second-to-last axis of b:

这里举最后两个例子说明一下即可

In [3]:
a = np.array([[1,2,3,4],[2,3,4,5,]])
b = np.array([1,2,3,4])
np.dot(a,b)

array([30, 40])

In [4]:
np.sum(a*b,axis=1)

array([30, 40])

In [5]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
c = np.dot(a, b)

In [6]:
c[1,2,3,3,2,1]

118443

In [7]:
sum(a[1,2,3,:]*b[3,2,:,1])

118443

## inner

`numpy.inner(a, b)`

Inner product of two arrays.

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

- Parameters:	
    a, b : array_like

    If a and b are nonscalar, their last dimensions must match.

- Returns:	
    out : ndarray

    out.shape = a.shape[:-1] + b.shape[:-1]

- Raises:	
    ValueError

    If the last dimension of a and b has different size.

In [8]:
x = np.arange(3*4*5).reshape(3,4,5)
y = np.arange(3*4*5).reshape(4,3,5)
z = np.inner(x, y)
z[1,2,1,2]

4330

In [9]:
sum(x[1,2,:]*y[1,2,:])

4330

## cross

叉乘 cross(x, y) = $ x \times y$

In [10]:
x = np.array([1,2,3])
y = np.array([2,3,4])
np.cross(x, y)

array([-1,  2, -1])

## vdot

- Return the dot product of two vectors. If the input argument is higher dimensions, it will be flattened first, and 
then, do the dot product.

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[1,2]])
np.vdot(a,b)

22

## outer

outer是a的第一个元素跟b的每一个元素相乘作为第一行，第二个元素跟b的每一个元素相乘作为第二个元素...

In [12]:
a = np.arange(6).reshape(3, 2)
b = np.arange(6).reshape(2, 3)
np.outer(a, b)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5],
       [ 0,  2,  4,  6,  8, 10],
       [ 0,  3,  6,  9, 12, 15],
       [ 0,  4,  8, 12, 16, 20],
       [ 0,  5, 10, 15, 20, 25]])

## kron
如果A是一个m×n的矩阵，而B是一个p×q的矩阵，克罗内克积则是一个mp×nq的分块矩阵

A = [a11, a12;
     a21, a22]
     
kron(A, B) = [a11B, a12B;
              a21B, a22B]

In [13]:
A = np.array([[1,2], [3,4]])
B = np.array([[1,3], [2,4]])
np.kron(A, B)

array([[ 1,  3,  2,  6],
       [ 2,  4,  4,  8],
       [ 3,  9,  4, 12],
       [ 6, 12,  8, 16]])

kron积还可以实现repeat功能

In [14]:
A = np.array([[1,2],[3,4]])
np.kron(np.ones((2,2)), A).astype('int')

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

## tensordot

## 其他操作

    exp(x)
    log(x)
    log10(x)
    sqrt(x)
    absolute(x)
    conjugate(x)
    negative(x)
    ceil(x)
    floor(x)
    fabs(x)
    hypot(x)
    fmod(x)
    maximum(x,y)
    minimum(x,y)

`hypot` 返回对应点 `(x,y)` 到原点的距离。

In [15]:
x = np.array([1,2,3])
y = np.array([4,5,4])
np.hypot(x,y)

array([4.12310563, 5.38516481, 5.        ])

In [16]:
np.fmod([1,2,3,4,5,6,7],2) #求余

array([1, 0, 1, 0, 1, 0, 1])

In [17]:
np.fmod([-1,-2,-3, 1, 2,3,4,5,6,7],2)

array([-1,  0, -1,  1,  0,  1,  0,  1,  0,  1])

In [18]:
np.remainder([-1,-2,-3, 1, 2,3,4,5,6,7],2)

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 1])

## 类型处理

    iscomplexobj
    iscomplex
    isrealobj
    isreal
    imag
    real
    real_if_close
    isscalar
    isneginf
    isposinf
    isinf
    isfinite
    isnan
    nan_to_num
    common_type
    typename

正无穷：

In [19]:
np.inf

inf

负无穷：

In [20]:
-np.inf

-inf

非法值（Not a number）：

In [21]:
np.nan

nan

检查是否为无穷：

In [22]:
np.isinf(1.0)

False

In [23]:
np.isinf(np.inf)

True

In [24]:
np.isinf(-np.inf)

True

非法值：

In [25]:
np.array([0]) / 0.0

/home/hecc/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan])

这并不会报错，而是返回一个非法值。

只有 `0/0` 会得到 `nan`，非0值除以0会得到无穷：

In [26]:
a = np.arange(5.0)
b = a / 0.0
b

/home/hecc/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/home/hecc/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, inf, inf, inf, inf])

`nan` 与任何数进行比较都是 `False`：

In [27]:
b == np.nan

array([False, False, False, False, False])

想要找出 `nan` 值需要使用 `isnan`：

In [28]:
np.isnan(b)

array([ True, False, False, False, False])

## 修改形状

    atleast_1d
    atleast_2d
    atleast_3d
    expand_dims
    apply_over_axes
    apply_along_axis
    hstack
    vstack
    dstack
    column_stack
    hsplit
    vsplit
    dsplit
    split
    squeeze

## apply_over_axes

In [29]:
a = np.arange(20).reshape(2,2,5)
print(a)
np.apply_over_axes(np.sum, a, (0,2))#将axis=0,2的两个方向加起来

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


array([[[ 70],
        [120]]])

## apply_along_axis

In [30]:
a = np.arange(20).reshape(4,5)
print(a)
f = lambda x:(x[0]+x[-1])/2

np.apply_along_axis(f, 0, a)#将axis=0,2的两个方向加起来

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([ 7.5,  8.5,  9.5, 10.5, 11.5])

## column_stack

In [31]:
a = np.array([1,2,3,3])#合并列向量为一个array
np.column_stack((a,a,a,a))

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

## split, hsplit, vsplit, array_split

In [32]:
a = np.arange(10)

In [33]:
np.split(a, 5)#必须是相等的维度, np.split(a, 3)会报错

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [34]:
print(np.split(a, [1,2,3,4]))
print(np.split(a, [1,2,3,5,12]))

[array([0]), array([1]), array([2]), array([3]), array([4, 5, 6, 7, 8, 9])]
[array([0]), array([1]), array([2]), array([3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]


In [35]:
a = np.arange(12).reshape(3,4)

In [36]:
np.split(a, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [37]:
np.hsplit(a, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [38]:
np.vsplit(a, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [39]:
np.split(a, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [40]:
a = np.arange(7)
np.array_split(a, [3])#可以分割成多个不同维度的, 尽可能多的分的均匀

[array([0, 1, 2]), array([3, 4, 5, 6])]

In [41]:
np.array_split(a, 4)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6])]

## 其他有用函数

|函数|主要功能|函数|主要功能|
|--|--|--|--|
|`fix`|取离零最近的整数|`trim_zeros`|删除头尾的零|
|`mod`|余数|`fliplr`|左右翻转|
|`amax`|最大值|`flipud`|上下翻转|
|`amin`|最小值|`rot90`|逆时针旋转90°|
|`ptp`|最大最小值的差|`diag`|对角线|
|`sum`|求和|`eye`|单位矩阵|
|`cumsum`|累积和|`select`|选择(下面具体解释)|
|`prod|求积`|`insert`|插入元素(感觉这个方法不咋常用)|
|`cumprod`|累积积|`extract`|筛选|
|`diff`|n阶差分|`roots`|返回多项式方程的根|
|`angle`|求复数的幅角|`poly`|由根推系数|
|`unwrap`|去除周期性的相位, 默认是2pi的周期|`any`|全部为零才为False|
|`sort_complex`|优先实部, 其次是虚部|`all`|全部为一才为True|
|`disp`|print|`unique`|唯一元素|

nansum, nanmax, nanargmax, nanargmin, nanmin, `nan` 开头的函数会进行相应的操作，但是忽略 `nan` 值。

## select

In [42]:
a = np.arange(10)
condlist = [a<3, a>6]
choicelist = [a, a**2]
np.select(condlist, choicelist)#两个彼此对应的操作, 小于3的还是a, 大于6的取平方, 其余地方为零

array([ 0,  1,  2,  0,  0,  0,  0, 49, 64, 81])

## extract

In [43]:
a = np.arange(16).reshape(4,4)
ind = np.mod(a, 3) == 1
np.extract(ind, a)

array([ 1,  4,  7, 10, 13])

In [44]:
a[ind]

array([ 1,  4,  7, 10, 13])

## insert

In [45]:
a = np.arange(12).reshape((3,4))
np.insert(a, 1, 100)

array([  0, 100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [46]:
np.insert(a, (1, 2), 100, axis=0)

array([[  0,   1,   2,   3],
       [100, 100, 100, 100],
       [  4,   5,   6,   7],
       [100, 100, 100, 100],
       [  8,   9,  10,  11]])

## root

`numpy.roots(p)`
- Return the roots of a polynomial with coefficients given in p.

The values in the rank-1 array p are coefficients of a polynomial. If the length of p is n+1 then the polynomial is described by:

 `p[0] * x**n + p[1] * x**(n-1) + ... + p[n-1]*x + p[n]`

In [47]:
np.roots((1, -2, 1))

array([1., 1.])

## poly
`numpy.poly`
`numpy.poly(seq_of_zeros)`

Find the coefficients of a polynomial with the given sequence of roots.

- Returns the coefficients of the polynomial whose leading coefficient is one for the given sequence of zeros (multiple roots must be included in the sequence as many times as their multiplicity; see Examples). A square matrix (or array, which will be treated as a matrix) can also be given, in which case the coefficients of the characteristic polynomial of the matrix are returned.

- Parameters:	
seq_of_zeros : array_like, shape (N,) or (N, N)

A sequence of polynomial roots, or a square array or matrix object.

- Returns:
c : ndarray

1D array of polynomial coefficients from highest to lowest degree:

c[0] * x**(N) + c[1] * x**(N-1) + ... + c[N-1] * x + c[N] where c[0] always equals 1.

- Raises:
ValueError

If input is the wrong shape (the input must be a 1-D or square 2-D array).

In [48]:
np.poly((1,1))

array([ 1., -2.,  1.])

## unique
`numpy.unique`(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)

In [49]:
a = np.array([10,3,2,5,4,5,5,5,5,5,6,7,8,9])

In [50]:
au, indice, inverse_indice, count= np.unique(a, return_index=True, return_inverse=True, return_counts=True)

In [51]:
au

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a[indice]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
au[inverse_indice]#将unique以后的数组返回到之前的数组

array([10,  3,  2,  5,  4,  5,  5,  5,  5,  5,  6,  7,  8,  9])

In [54]:
count #各个元素出现的次数, 对应的是unique以后的数组

array([1, 1, 1, 6, 1, 1, 1, 1, 1])

In [55]:
a = np.array([[1,2,3,4],[1,4,2,1],[1,2,3,4],[1,2,3,5],[1,4,2,1]])

In [56]:
au, indice, inverse_indice, count= np.unique(a, return_index=True, return_inverse=True, return_counts=True, axis=0)

In [57]:
au#这是对于数组的unique, 设定axis就可以, 其余参数完全一致

array([[1, 2, 3, 4],
       [1, 2, 3, 5],
       [1, 4, 2, 1]])