## Common mathematic function in MATLAB
MATLAB中的一些常用函数, 与Python中的对应函数

In [ ]:
import numpy as np

## find , ismember (MATLAB), where (Python)

In [9]:
a = np.array([3,4,5,1,2,4,6])
np.where(a==4)

(array([1, 5]),)

In [10]:
np.where(a>4)

(array([2, 6]),)

In [11]:
a = np.arange(12).reshape(4,3)
np.where(a==4)

(array([1]), array([1]))

In [12]:
np.where(a>9)

(array([3, 3]), array([1, 2]))

返回的实际上分别为两个方向的索引,ij两个, 这里也即为(3,1), (3,2)两个索引, 所以如果为了和MATLAB保持一致, 我们可以使用zip函数

In [19]:
i, j = np.where(a>9)
list(zip(list(i), list(j)))

[(3, 1), (3, 2)]

尝试实现ismember(A, B, 'rows')

In [25]:
a = np.array([[1,2,3],[3,4,5],[4,5,6],[6,7,8]])
b = np.array([[3,4,5]])
b = np.repeat(b, 4, axis=0)
np.where(a==b)

(array([1, 1, 1]), array([0, 1, 2]))

返回的实际上即为condition对应的索引, 也即为a对应condition的索引, 所以如果为了返回是那一行对应相等就得再加一点条件

In [34]:
c = np.where(a==b)
if np.size(c[0]) == np.shape(a)[1]:
    print('The %drd rows match'%c[0][0])
else:
    print('No match')

The 1rd rows match


## repmat (MATLAB) & repeat (Python)

上述的代码中, 我使用到了repeat函数, 实际上与MATLAB中的repmat函数是一致的.

`numpy.repeat`
`numpy.repeat(a, repeats, axis=None)`

Repeat elements of an array.

- Parameters:	
a : array_like

- Input array.

- repeats : int or array of ints

The number of repetitions for each element. repeats is broadcasted to fit the shape of the given axis.

- axis : int, optional

The axis along which to repeat values. By default, use the flattened input array, and return a flat output array.

- Returns:	
repeated_array : ndarray

- Output array which has the same shape as a, except along the given axis.

In [36]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [37]:
np.repeat([1,2,3], 4) 

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [39]:
np.repeat(np.array([1,2,3]), 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [40]:
a = np.array([[1,2,3,4]])
np.repeat(a, 4, axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [45]:
np.repeat(a, 4, axis=1)

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

In [46]:
a = np.arange(2*2*2).reshape(2,2,2)
np.repeat(a, 2)#不设置axis就先把它flat， 然后进行repeat

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7])

In [55]:
a = np.arange(12).reshape(4,3)
np.repeat(a, [1,2,3,4], axis=0)#设定每一行repeat的次数

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 9, 10, 11],
       [ 9, 10, 11],
       [ 9, 10, 11]])

## sort, sortrows (MATLAB)  & sort (Python) 相关函数

`numpy.sort(a, axis=-1, kind='quicksort', order=None)[source]`
- Return a sorted copy of an array.

- Parameters:	
  a : array_like

  Array to be sorted.

- axis : int or None, optional

  Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

- kind : {‘quicksort’, ‘mergesort’, ‘heapsort’}, optional

  Sorting algorithm. Default is ‘quicksort’.

- order : str or list of str, optional

  When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

- Returns:	
  sorted_array : ndarray

Array of the same type and shape as a.

In [56]:
a = np.array([1,3,2,6,4,8,3,9,1,0,2])
np.sort(a)

array([0, 1, 1, 2, 2, 3, 3, 4, 6, 8, 9])

In [64]:
import random
a = list(range(16))
random.shuffle(a)
a = np.array(a).reshape(4,4)
print('a:\n', a)

a:
 [[ 4  9 12  1]
 [ 0  2  7 14]
 [ 5  6 13  3]
 [11 15 10  8]]


In [65]:
np.sort(a)#未指明axis, 按照最后一个axis进行排序

array([[ 1,  4,  9, 12],
       [ 0,  2,  7, 14],
       [ 3,  5,  6, 13],
       [ 8, 10, 11, 15]])

In [66]:
np.sort(a, axis=0)

array([[ 0,  2,  7,  1],
       [ 4,  6, 10,  3],
       [ 5,  9, 12,  8],
       [11, 15, 13, 14]])

## sortrows
numpy v1.14 出现了order的参数, 可以实现优先级排序, 也即为类似于sortrows

所以我们自行构造一个标签就可以了

In [71]:
a = [(1,2,4,5,6), (1,2,3,4,5), (1,4,6,3,2), (2,1,3,4,5)]
order = [(str(i), int) for i in range(5)]
a = np.array(a, dtype=order)
b = np.sort(a, order=[str(i) for i in range(5)])
print(b)

[(1, 2, 3, 4, 5) (1, 2, 4, 5, 6) (1, 4, 6, 3, 2) (2, 1, 3, 4, 5)]


有一个lexsort函数专门来实现这个功能

##  lexsort
`numpy.lexsort`
`numpy.lexsort(keys, axis=-1)`
- Perform an indirect sort using a sequence of keys.

- Given multiple sorting keys, which can be interpreted as columns in a spreadsheet, lexsort returns an array of integer indices that describes the sort order by multiple columns. The last key in the sequence is used for the primary sort order, the second-to-last key for the secondary sort order, and so on. The keys argument must be a sequence of objects that can be converted to arrays of the same shape. If a 2D array is provided for the keys argument, it’s rows are interpreted as the sorting keys and sorting is according to the last row, second last row etc.

- Parameters:	
- keys : (k, N) array or tuple containing k (N,)-shaped sequences

  The k different “columns” to be sorted. The last column (or row if keys is a 2D array) is the primary sort key.

- axis : int, optional

  Axis to be indirectly sorted. By default, sort over the last axis.

- Returns:	
- indices : (N,) ndarray of ints

Array of indices that sort the keys along the specified axis.

In [85]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
[[a[i], b[i]] for i in ind]

[[1, 0], [1, 9], [3, 0], [4, 1], [4, 2], [4, 4], [5, 4]]