## numpy.loadtxt
numpy.loadtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, 
              usecols=None, unpack=False, ndmin=0)

In [1]:
%%writefile test.txt
1 2 3 4 
2 3 4 5
3 4 5 6
4 5 6 7

Overwriting test.txt


In [2]:
import numpy as np
a = np.loadtxt('test.txt')#最普通的loadtxt
print(a)

[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]
 [4. 5. 6. 7.]]


In [3]:
a = np.loadtxt('test.txt', dtype=int)
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [4]:
%%writefile test.txt
A B C
1 2 3
4 5 6
7 8 9

Overwriting test.txt


In [5]:
a = np.loadtxt('test.txt', skiprows=1, dtype=int)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
%%writefile test.txt
A B C
1 2 3
# AAA
4 5 6
7 8 9

Overwriting test.txt


In [7]:
a = np.loadtxt('test.txt', dtype=int, skiprows=1, comments='#')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
%%writefile test.txt
A B C
1, 2, 3
# AA AAA
4, 5, 6
7, 8, 9

Overwriting test.txt


In [9]:
a = np.loadtxt('test.txt', dtype=int, skiprows=2, comments='#', delimiter=',', usecols=(0, 2))
print(a)

[[4 6]
 [7 9]]


In [10]:
(a, b) = np.loadtxt('test.txt', dtype=int, skiprows=1, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[1 4 7] [3 6 9]


In [11]:
def add_one(x):
    return int(x)+1#注意到这里使用的字符的数据结构
(a, b) = np.loadtxt('test.txt', dtype=int, skiprows=1, converters={0:add_one}, comments='#', delimiter=',', usecols=(0, 2), unpack=True)
print(a, b)

[2 5 8] [3 6 9]


##  `numpy.genfromtxt`
`numpy.genfromtxt`(fname, dtype=<type 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes'

这里关键词与loadtxt的一致的, 其用法也基本一致的，下面讲一下其他特有的关键字的用法

In [12]:
%%writefile test.txt
AA AA AA
1 2 3 
4 5 6
CC CC CC
BB BB BB

Overwriting test.txt


In [13]:
a = np.genfromtxt('test.txt', skip_header=1, skip_footer=2, dtype=int)#跳过头尾, 都是跳过前n行或者倒数的后n行
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
%%writefile test.txt
AA BB CC
1 2 3
4 5 6
CC CC CC
BB BB BB

Overwriting test.txt


In [15]:
a = np.genfromtxt('test.txt', skip_header=1, skip_footer=2, dtype=int, names=['AA', 'BB', 'CC'])
print(a,'\n', a['AA'])#设定的names可以将a变成一个以names为key的字典

[(1, 2, 3) (4, 5, 6)] 
 [1 4]


In [16]:
%%writefile test.txt
10, 4, 4, 
10, 5, 6, 5

Overwriting test.txt


In [17]:
a = np.genfromtxt('test.txt',delimiter=',', dtype=None, missing_values={0:10}, filling_values=100)
print(a)
#missing_values 标记为缺失,字典， key为column, value为缺失的替换, {0:10}表示第一列的10原本是缺失的， 但是这里用4填补

#filling_values进行填补

[[100   4   4 100]
 [100   5   6   5]]


In [18]:
a = np.genfromtxt('test.txt',delimiter=',', dtype=None, missing_values={0:10}, filling_values={0:100, 3:999})
print(a)
#missing_values 标记为缺失,字典， key为column, value为缺失的替换, {0:10}表示第一列的10原本是缺失的， 但是这里用4填补

#filling_values也可以使用字典进行不同列的填补

[[100   4   4 999]
 [100   5   6   5]]
