## 结构化数组

我们希望一个二维array, 每一列代表一个不同的属性, 并且调用可以灵活调用某一个属性, 其实就是类似于字典一样的结构了

In [5]:
import numpy as np
a = [(1,2), (3,4), (5,6)]
dtype=[('A', int), ('B', int)]#这里第一列为A属性, 第二列为B属性
a = np.array(a, dtype=dtype)

In [6]:
a['A']

array([1, 3, 5])

In [7]:
a['B']

array([2, 4, 6])

实际上之前我们用过这样的属性来对数组进行优先级排序

In [11]:
a = [(1,3,4), (1,2,3), (1,4,5), (1,2,4)]
dt = [(str(i), int) for i in range(3) ]
a = np.array(a, dtype=dt)

In [13]:
c = np.sort(a, order=[str(i) for i in range(3)])
print(c)

[(1, 2, 3) (1, 2, 4) (1, 3, 4) (1, 4, 5)]


更一般的， 我们可以建立一个person的数组

In [15]:
ptype = [('name', 'S10'), ('age', int), ('height', float)]
person = np.zeros((2,3), ptype)

In [17]:
person['name'] = [['A', 'B', 'C'],['D', 'E', 'F']]
person['age'] =np.arange(6).reshape(2,3)
person['height'] = np.arange(150, 156).reshape(2,3)

In [18]:
person

array([[(b'A', 0, 150.), (b'B', 1, 151.), (b'C', 2, 152.)],
       [(b'D', 3, 153.), (b'E', 4, 154.), (b'F', 5, 155.)]],
      dtype=[('name', 'S10'), ('age', '<i8'), ('height', '<f8')])

In [19]:
person[0,0]

(b'A', 0, 150.)

从文本中读取结构化数组

In [20]:
%%writefile people.txt
name age weight
amy 11 38.2
john 10 40.3
bill 12 21.2

Writing people.txt


In [29]:
person = np.loadtxt('people.txt',  skiprows=1, dtype=[('name', 'S10'), ('age', int), ('weight', float)])

In [30]:
person

array([(b'amy', 11, 38.2), (b'john', 10, 40.3), (b'bill', 12, 21.2)],
      dtype=[('name', 'S10'), ('age', '<i8'), ('weight', '<f8')])

## 记录数组

In [32]:
dt = [('mass', float), ('velocity', float)]
particle = np.rec.fromrecords([(1,1), (2,1), (3,1)], dtype=dt)

In [33]:
particle.mass #record结构的特殊调用方式

array([1., 2., 3.])

In [35]:
particle['velocity']

array([1., 1., 1.])

In [37]:
particals = np.array([(1,1), (1,2), (2,1), (1,3)],
                     dtype = dt)

也可以使用结构数组转化数据类型为record array

In [40]:
a = particals.view(np.recarray)

In [41]:
a.mass

array([1., 1., 2., 1.])